name: Run Tests on Push

on: [push] # ירוץ בכל פעם שתעשי Push

jobs:
  test:
    runs-on: ubuntu-latest # המחשב של גיטהאב הוא לינוקס

    steps:
      # 1. מוריד את הקוד שלך
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. מתקין פייתון
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. מתקין את הספריות מהקובץ requirements.txt
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. מריץ את הטסטים (במקביל - 2 עובדים)
      - name: Run Tests
        run: pytest -n 2 -v